import type { Metadata } from "next";
import { Outfit, Poppins, Raleway } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
})

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
})

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Little Learners School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${raleway.variable} ${poppins.variable} font-outfit antialiased flex justify-center items-center py-2`}
      >
        <main className="w-full max-w-[1400px] px-4 border">
          {children}
        </main>
      </body>
    </html>
  );
}
